spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: redispass

cocro:
  jwt:
    issuer: "cocro-api"
    secret: "xdF/mP/gUVw+P7G3Quks1TuyxyYUf/A04fxMGxqKJjIAEzab3wDSxPnr/KaukNfRsR8wlpZ6sTvZhLr6uw90Hw=="
    expirationSeconds: 86400
  session:
    heartbeat:
      grace-period-ms: 30000
      check-interval-ms: 15000
    flush:
      threshold: 50
      idle-check-ms: 30000
